// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search actors by name
	// (GET /actors/search)
	GetActorsSearch(c *gin.Context, params GetActorsSearchParams)
	// Get actor by ID
	// (GET /actors/{id})
	GetActorsId(c *gin.Context, id int)
	// Login and obtain JWT token
	// (POST /login)
	PostLogin(c *gin.Context)
	// Logout from account
	// (POST /logout)
	PostLogout(c *gin.Context)
	// Get popular movies
	// (GET /movies/popular)
	GetMoviesPopular(c *gin.Context, params GetMoviesPopularParams)
	// Search movies by name
	// (GET /movies/search)
	GetMoviesSearch(c *gin.Context, params GetMoviesSearchParams)
	// Get movie by ID
	// (GET /movies/{id})
	GetMoviesId(c *gin.Context, id int)
	// Delete movie rate
	// (DELETE /rating)
	DeleteRating(c *gin.Context, params DeleteRatingParams)
	// Rate a movie
	// (POST /rating)
	PostRating(c *gin.Context, params PostRatingParams)
	// Register new account
	// (POST /register)
	PostRegister(c *gin.Context)
	// Delete a review for a movie
	// (DELETE /reviews/{movie_id})
	DeleteReviewsMovieId(c *gin.Context, movieId int)
	// Get reviews for a movie
	// (GET /reviews/{movie_id})
	GetReviewsMovieId(c *gin.Context, movieId int)
	// Create or update a review for a movie
	// (POST /reviews/{movie_id})
	PostReviewsMovieId(c *gin.Context, movieId int)
	// Get profile of user
	// (GET /users/{id})
	GetUsersId(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetActorsSearch operation middleware
func (siw *ServerInterfaceWrapper) GetActorsSearch(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActorsSearchParams

	// ------------- Required query parameter "prompt" -------------

	if paramValue := c.Query("prompt"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument prompt is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "prompt", c.Request.URL.Query(), &params.Prompt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter prompt: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActorsSearch(c, params)
}

// GetActorsId operation middleware
func (siw *ServerInterfaceWrapper) GetActorsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActorsId(c, id)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogout(c)
}

// GetMoviesPopular operation middleware
func (siw *ServerInterfaceWrapper) GetMoviesPopular(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMoviesPopularParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", c.Request.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMoviesPopular(c, params)
}

// GetMoviesSearch operation middleware
func (siw *ServerInterfaceWrapper) GetMoviesSearch(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMoviesSearchParams

	// ------------- Required query parameter "prompt" -------------

	if paramValue := c.Query("prompt"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument prompt is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "prompt", c.Request.URL.Query(), &params.Prompt)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter prompt: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMoviesSearch(c, params)
}

// GetMoviesId operation middleware
func (siw *ServerInterfaceWrapper) GetMoviesId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMoviesId(c, id)
}

// DeleteRating operation middleware
func (siw *ServerInterfaceWrapper) DeleteRating(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteRatingParams

	// ------------- Required query parameter "movie_id" -------------

	if paramValue := c.Query("movie_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument movie_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "movie_id", c.Request.URL.Query(), &params.MovieId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRating(c, params)
}

// PostRating operation middleware
func (siw *ServerInterfaceWrapper) PostRating(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostRatingParams

	// ------------- Required query parameter "movie_id" -------------

	if paramValue := c.Query("movie_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument movie_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "movie_id", c.Request.URL.Query(), &params.MovieId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "rating" -------------

	if paramValue := c.Query("rating"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument rating is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "rating", c.Request.URL.Query(), &params.Rating)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter rating: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRating(c, params)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRegister(c)
}

// DeleteReviewsMovieId operation middleware
func (siw *ServerInterfaceWrapper) DeleteReviewsMovieId(c *gin.Context) {

	var err error

	// ------------- Path parameter "movie_id" -------------
	var movieId int

	err = runtime.BindStyledParameterWithOptions("simple", "movie_id", c.Param("movie_id"), &movieId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteReviewsMovieId(c, movieId)
}

// GetReviewsMovieId operation middleware
func (siw *ServerInterfaceWrapper) GetReviewsMovieId(c *gin.Context) {

	var err error

	// ------------- Path parameter "movie_id" -------------
	var movieId int

	err = runtime.BindStyledParameterWithOptions("simple", "movie_id", c.Param("movie_id"), &movieId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReviewsMovieId(c, movieId)
}

// PostReviewsMovieId operation middleware
func (siw *ServerInterfaceWrapper) PostReviewsMovieId(c *gin.Context) {

	var err error

	// ------------- Path parameter "movie_id" -------------
	var movieId int

	err = runtime.BindStyledParameterWithOptions("simple", "movie_id", c.Param("movie_id"), &movieId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostReviewsMovieId(c, movieId)
}

// GetUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/actors/search", wrapper.GetActorsSearch)
	router.GET(options.BaseURL+"/actors/:id", wrapper.GetActorsId)
	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.POST(options.BaseURL+"/logout", wrapper.PostLogout)
	router.GET(options.BaseURL+"/movies/popular", wrapper.GetMoviesPopular)
	router.GET(options.BaseURL+"/movies/search", wrapper.GetMoviesSearch)
	router.GET(options.BaseURL+"/movies/:id", wrapper.GetMoviesId)
	router.DELETE(options.BaseURL+"/rating", wrapper.DeleteRating)
	router.POST(options.BaseURL+"/rating", wrapper.PostRating)
	router.POST(options.BaseURL+"/register", wrapper.PostRegister)
	router.DELETE(options.BaseURL+"/reviews/:movie_id", wrapper.DeleteReviewsMovieId)
	router.GET(options.BaseURL+"/reviews/:movie_id", wrapper.GetReviewsMovieId)
	router.POST(options.BaseURL+"/reviews/:movie_id", wrapper.PostReviewsMovieId)
	router.GET(options.BaseURL+"/users/:id", wrapper.GetUsersId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa0Y/TuBP+Vyz/fg93UrUtByehvi1wrBZxJ8SCeEBoNU0mrSGxw3jSvVL1fz/ZTrbN",
	"1mnTW7jton1rY3s8nu/zzGcnS5mYojQaNVs5XkqbzLAA//M0YUPuR0mmRGKF/vEUdYr+OS9KlGOpNOMU",
	"Sa4GUqXx5xoK3GixTEpPXUNJJlM5XpbAs0iH1aB5YiafMWE35Aw14bZbB04ds/ynmauIZXBxCHMwFv7H",
	"/wkzOZb/G66DN6wjNwxhW9sHIli4/5BWOW+4MjEmR9CuaerW1H+KEILIFF1BMHOkucKrOAbGMlIXBANJ",
	"mCNYvEyBfXQyQwWwHEv/YBAbMEddYdwVy4RQXOZKf4nOxorzOFe4SCeXXSv0jXPDeAlzJJi2Pc1yA7x2",
	"VVfF5OawxFSa47YPN7vbYox7b4HdMrfIVzhOdq6arkft8yk6JzacaM+Zqy+Yxom62x3Gv/lAUCuL1GFv",
	"22VHH0wqUry4cFshuPsMrEpOq8Bev0W80+7pOg4z5tLN9wyBkJreE//vZRO7Vx/eycGGCd9604bzQunM",
	"uPEp2oRUycpoOZbPlcYCxBkwXsFCnL45l9dLbxov3EZMsG6cI9kw9tHJ6GTkt2qJGkolx/LxyejksRxI",
	"tzH9QochEw0tAiWzkIt9vB144Jw4T+VYniH7HGQvQj9ngaBARpfFPi6lchN+rZAWssmPjgFF6XhD+LVS",
	"5PBnqrCOBsQy6CfX2ZZG24DDb6ORT5dlmavEuzP8bN3ilhtGbpNCV4MbAX+tLAuTicxUOhV1nl4N5O/B",
	"k8RoxrAFdzvVpj8SGepVMrY9OteMpCEXf3gjnrFVUQAt5FgGPGo/xWQhfOxdnwbZpUpX+3E9Tzsw9Sn8",
	"GlKV9oFzvd068OwdxV2IhtIaCZhfkUiRQeUeuyejJ3eE3V+GxUvHpCOm0Bly4I+jz/mLQJ7cTJV3x1Xy",
	"bd68MZZf+y6BDmj5mUkXt1heCdZeGUo7M3pv0bVa3aTo6pYsbHvK5gvqfwnERZUkaG1W5SJE2LPz0R3R",
	"4r2GimeG1Dc8QoLWVdmnoo16/PGTyypr+noaCtCpMBMGpcWrD+9EwKhhsql4L5VdnzhNOhEknConcx9A",
	"7Anihk6KoGgqFhmZQkASZK6Hz6tDOyxNWeVAuwqZrwf2Td2xn0Jx6ntnARvEB1r1bc/AH6dk6rrXW8kU",
	"xrKo4ydCOIXSwq/9uKtS2+kWH/br1UCHe6tXD0U56NUmUseuV2satvRqjew+vRpw/Zn0qm940KuHZAbP",
	"lU29ur61SDHHcKnUps4L/7y+E+mVD64vJr4HhdoLDG6I4Gt6twLilBmLkgWb2h8Rgil4Biy0YbEwFW0S",
	"M7qWK7C+c3ac9OkrRAJNaoIRMDbXmXHl+OP51KFAqJm429Te+7tDqGphfudErXWun0l4S+KXkswEJvki",
	"SH6h9BxylQJj+uv9JeFbYBQQSFjnt+assfMc87bpdY9P5b2OW0dampr4C41X7WMM+XtxO1w2SWDVo1aF",
	"MV4e9NQ7P7JkeW+OtmQF7/qWrND75ypZ0AQhM7ROHoNOIX3X9Ood5V7npfrF0/aBaSvU9brXqD/I7X1y",
	"m65D1mLWrkL0X3Lre1S6HS8oD34F+d2qX52njkF7rTNuMgM97ci4wpAwPEMSUPEsaLT7m1ifEzohZkhU",
	"ZQqdKdbVd6eF9t9dvHe9jvTq4sZ2aN7/bH+J4c8D/T8sqU9IkS9L6qxy+xTfgwaxA3dEGDiAjl0WtK9I",
	"w8dOwmTCUTDYsEjzhlkV5fVnBuPhMDcJ5DNjefx09HQ0hFLJ1afVPwEAAP//zCZuILAlAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
