apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
  
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      username: ${CLICKHOUSE_ADMIN}
      password: ${CLICKHOUSE_PASSWORD}
      defaultDatabase: default
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}