name: Python Common Packages Lint & Test

on:
  push:
    branches:
      - master
    paths:
      - "backend/pkg/python/**"
  pull_request:
    paths:
      - "backend/pkg/python/**"

jobs:
  format-lint:
    name: Python Format & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Formatting & Linting Tools
        run: pip install black flake8

      - name: Check Formatting (black)
        run: black --check backend/pkg/python/

      - name: Run Linter (flake8)
        run: flake8 backend/pkg/python/

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    needs: format-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Find and Install Requirements
        run: |
          find backend/pkg/python -name "requirements.txt" -exec pip install -r {} +

      - name: Find and Run Python Tests
        run: |
          find backend/pkg/python -name "tests" -type d -exec pytest {} +
