name: Go Common Packages Build & Test

on:
  push:
    branches:
      - master
    paths:
      - "backend/pkg/go/**"
  pull_request:
    paths:
      - "backend/pkg/go/**"

jobs:
  build:
    name: Build Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Go Pkg
        working-directory: backend/pkg/go
        run: go build ./...

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run Go Pkg Tests
        working-directory: backend/pkg/go
        run: go test ./...
